MissingDogsWebsite/thing/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MissingDogsEntities : DbContext
    {
        public MissingDogsEntities()
            : base("name=MissingDogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<missing> missings { get; set; }
    }
}

MissingDogsWebsite/thing/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'A:\MissingDogsSite\MissingDogsWebsite\thing\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MissingDogsWebsite/thing/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MissingDogsWebsite/thing/Models/missing.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class missing
    {
        public int Id { get; set; }

        [DisplayName ("Dog Name")]
        public string DogName { get; set; }

        [DisplayName("Dog Breed")]
        public string DogBreed { get; set; }

        [DisplayName("Last Known Location")]
        public string LastKnownLocation { get; set; }

        [DisplayName("Contact Number")]
        public string ContactNumber { get; set; }


        public Nullable<bool> Found { get; set; }
    }
}

MissingDogsWebsite/thing/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thing.Models;
namespace thing.Controllers
{
    public class HomeController : Controller
    {
        private MissingDogsEntities db = new MissingDogsEntities();
        public ActionResult Index()
        {
            return View(db.missings.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MissingDogsWebsite/thing/Controllers/missingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thing.Models;

namespace thing.Controllers
{
    public class MissingsController : Controller
    {
        private MissingDogsEntities db = new MissingDogsEntities();

        // GET: missings
        public ActionResult Index()
        {
            var lostDogs = db.missings.Where(b => b.Found == false);
            return View(lostDogs);
        }

        // GET: missings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missing missing = db.missings.Find(id);
            if (missing == null)
            {
                return HttpNotFound();
            }
            return View(missing);
        }
        // GET: missing/Found
        public ActionResult Found()
        {
            var foundDogs = db.missings.Where(b => b.Found == true);
            return View(foundDogs);
        }
        // GET: missings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: missings/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DogName,DogBreed,LastKnownLocation,ContactNumber")] missing missing)
        {
            if (ModelState.IsValid)
            {
                db.missings.Add(missing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(missing);
        }

        // GET: missings/Edit/5
        public ActionResult Edit(int? id)
        {
            // todo: update this 

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missing missing = db.missings.Find(id);
            if (missing == null)
            {
                return HttpNotFound();
            }
            return View(missing);
        }

        // POST: missings/Edit/5
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DogName,DogBreed,LastKnownLocation,ContactNumber,Found")] missing missing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(missing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(missing);
        }

        // GET: missings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missing missing = db.missings.Find(id);
            if (missing == null)
            {
                return HttpNotFound();
            }
            return View(missing);
        }

        // POST: missings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            missing missing = db.missings.Find(id);
            db.missings.Remove(missing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MissingDogsWebsite/thing/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MissingDogsWebsite/thing/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MissingDogsWebsite/thing/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MissingDogsWebsite/thing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Missing Dogs Found", "Index", "Missings", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Currently Missing", "Index", "missings")</li>
                    <li>@Html.ActionLink("Report", "Create", "missings")</li>
                    <li>@Html.ActionLink("Found", "found", "missings")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MissingDogsWebsite/thing/Views/missings/Create.cshtml
@model thing.Models.missing

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>missing</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DogName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DogName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DogName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DogBreed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DogBreed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DogBreed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastKnownLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastKnownLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastKnownLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MissingDogsWebsite/thing/Views/missings/Delete.cshtml
@model thing.Models.missing

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>missing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DogName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DogBreed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogBreed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastKnownLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastKnownLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MissingDogsWebsite/thing/Views/missings/Details.cshtml
@model thing.Models.missing

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>missing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DogName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DogBreed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogBreed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastKnownLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastKnownLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MissingDogsWebsite/thing/Views/missings/Edit.cshtml
@model thing.Models.missing

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>missing</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DogName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DogName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DogName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DogBreed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DogBreed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DogBreed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastKnownLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastKnownLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastKnownLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Found, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Found, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Found, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MissingDogsWebsite/thing/Views/missings/Index.cshtml
@model IEnumerable<thing.Models.missing>

@{
    ViewBag.Title = "Missing Animals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Missing Dogs</h2>
<p>These are the Animals in our database that are currently missing. To report a found animal please use contact number listed with posting.</p>
<p>
    @Html.ActionLink("Report new missing dog", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DogName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DogBreed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastKnownLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Found)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DogName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DogBreed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastKnownLocation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Found)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
          
        </td>
    </tr>
}

</table>

MissingDogsWebsite/thing/Views/missings/found.cshtml
@model IEnumerable<thing.Models.missing>

@{
    ViewBag.Title = "Found Animals Animals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Found Dogs</h2>
<p>These are Dogs that have been reunited with there owners! YAY!</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DogName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DogBreed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastKnownLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Found)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DogName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DogBreed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastKnownLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Found)
            </td>
            <td>
           @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
           @Html.ActionLink("Details", "Details", new { id = item.Id }) |

            </td>
        </tr>
    }

</table>